### ISSUE TITLE
NullPointerException on "new CalendarPanel()"

### ISSUE THREAD

**Issue by tcrass** [LGoodDatePicker/LGoodDatePicker#102]
Hi there,

observerd in version 11.0.0:

When instancing a CalendarPanel using the parameter-less constructor

`CalendarPanel calendarPanel = new CalendarPanel();`

I get a NullPointerException:

```
java.lang.NullPointerException: null
	at com.github.lgooddatepicker.components.CalendarPanel.<init>(CalendarPanel.java:253)
	at com.github.lgooddatepicker.components.CalendarPanel.<init>(CalendarPanel.java:211)
	...
```

It turns out that in the line in which the exception occurs...

`displayedYearMonth = YearMonth.now(datePickerSettings.getClock());`

...the datePickerSettings parameter is null (obviously, when looking at the calling site in line 211).

It's only in line 294 of the constructor that the `setSettings(datePickerSettings)` function gets called, which ensures that a default settings object is created in case the passed datePickerSettings are null.

I currently don't have the possibility to fork the project and to work on this issue myself, but perhaps a simple solution would be to move the `setSettings(datePickerSettings)` call right to the start of the constructor and to replace `displayedYearMonth = YearMonth.now(datePickerSettings.getClock());` with `displayedYearMonth = YearMonth.now(settings.getClock());`?

Cheers -- Torsten

**Comment by WiseEagleOwl** [comment]
@tcrass 
Hi Torsten,

Thank you for taking the time to report an issue with *LGoodDatePicker*. I really appreciate that you took the time to provide a deeper analysis of the root cause :+1: . A `NullPointerException` thrown when calling `new CalendarPanel()`was already identified and fixed on *master*. 
Due to your issue report I have created a new release of version of *LGoodDatePicker*: `v11.0.2`. 
You [can find the release here](
https://github.com/LGoodDatePicker/LGoodDatePicker/releases/tag/v11.0.2-Standard).

Can you please verify that `v11.0.2` fixes your issue too?

**Comment by BlakeTNC** [comment]
@WiseEagleOwl, FYI, v11.0.2 demo is running successfully on double click under Mac OS Catalina, JDK 1.8. and Win 10 JDK 1.8. 
-Blake

**Comment by WiseEagleOwl** [comment]
@BlakeTNC Thank you for testing the demo of the new release on Mac and Windows :+1:

**Comment by tcrass** [comment]
Dear Wise Eagle Owl,

> Can you please verify that `v11.0.2` fixes your issue too?

yes, instantiating a CalendarPanel using the parameter-less constructor works perfectly in 11.0.2!

Thank for the fix -- can't wait to see it appearing on the public Maven Central channel... :)

Cheers, Torsten
