### ISSUE TITLE
Feature request: Make LGoodDatePicker compatible with Java 1.7 or below, using the JSR-310 backport.

### ISSUE THREAD

**Issue by victorqedu** [LGoodDatePicker/LGoodDatePicker#14]
When I try to complile in Java 1.7 the error is:
java.lang.UnsupportedClassVersionError: com/github/lgooddatepicker/datepicker/DatePicker : Unsupported major.minor version 52.0

I can't change to Java 1.8, I have some missing functionality. Can I use LGoodDatePicker with 1.7?

Thank you.

**Comment by BlakeTNC** [comment]
Hello victorqedu,

I'm sorry, it's not currently possible to use LGoodDatePicker with any version lower than Java 1.8. The reason is that LGoodDatePicker uses the "java.time" (JSR-310) package that was only officially included with Java version 1.8. Using the new Java time libraries was a vital design decision. The new time library addresses serious deficiencies that existed in the original ("java.util.Date") time libraries. So it was either all or nothing with choosing to build the library to use Java 1.8 and above. 

You mentioned that you can't change to Java 1.8. I imagine that most projects could theoretically be upgraded to the latest Java version, unless 1) there is some administrative policy against the upgrade, or 2) There is some dependency being used that will not work in Java 1.8. Java has always been big on backwards compatibility, so if any code changes would be required, they would be minor.

I'm not sure what your other considerations are, but out of curiosity let me know if you change your mind about transitioning to Java 1.8. Also please let me know if there's any other way I can assist.

To be totally accurate, there is one possibility for (sort of) using LGoodDatePicker with Java 1.7, but it might be infeasible. It would basically require motivated programmer, significant effort, and a code fork. The library would have to be adapted (almost rewritten) to work with [Joda Time](http://www.joda.org/joda-time/), which has similar time handling classes as Java 1.8. I wouldn't be doing that project myself, but if another programmer decided they wanted to do that, then I would support them if desired, as a consultant for the LGoodDatePicker code base.

warm regards,
Blake

**Comment by victorqedu** [comment]
I want to migrate on Java1.8 but in 1.8 the old module for Microsoft Access is not available.
I tried another Java MSAccess module(UCanAccess) but lasttime I checked it was loading the whole mdb file in memmory and it was very slow on big mdb's. Also I found some incompatibilities about PCKS11 that should be fixed easy.
I looked a lot and it seems that LGoodDatePicker is the best module available and I want to use it.
Another problem is that all computers where my application is installed have jre 1.7 and updates disabled. If I publish a new version with LGoodDatePicker  than I must go to all computers and update Java mannualy. This is a lot of work.
I need to replace my old date module because I found a memory leak.

I guess that it would be easier for users and developers if there would be a single library compatible with 1.7 and 1.8. If the code would detect java version and use the appropriate code. 

You made a great job with this module. 
Thank you.

**Comment by BlakeTNC** [comment]
Hello victorqedu,
   I was just doing some research, and it turns out that there is a back port available for the Java 8 time libraries (JSR-310 backport) that is reported to work with Java 1.7 and 1.6.

The back port exists at the following links:
http://www.threeten.org/threetenbp/

https://github.com/ThreeTen/threetenbp

This backport could theoretically provide an easier way to make LGoodDatePicker compatible with older versions of Java. I will consider the possibility of modifying the project to be compatible with older versions. I would not expect this enhancement to happen soon though. If this feature is added to the library, I would update this issue with any news.

warm regards,
Blake

**Comment by victorqedu** [comment]
Thank you, I will try it and reply.

**Comment by BlakeTNC** [comment]
Since you are going to try it, here are some details you might find useful: 
Besides importing the JSR-310 back port library, I'm guessing that the (entire) code base would need to be reviewed for Java-8-specific syntax and features. Of course any of those sorts of features will be flagged as errors as soon as the compiler was told to only use Java 1.7, so at least -finding- those bits of code would be pretty easy. Fixing them might not necessarily be easy, I won't know until I try. Also FYI, it looks like the JSR-310 back port is available through Apache maven.
warm regards,
Blake

**Comment by BlakeTNC** [comment]
Hello victorqedu, 
   Today I created and released a backport version of the LGoodDatePicker library. The first backport release is here [LGoodDatePicker Backport 5.3.2](https://github.com/LGoodDatePicker/LGoodDatePicker/releases/tag/v5.3.2-Backport)

This first backport release is experimental, so please let me know if it works for you or not.
Thank you!

warm regards,
Blake
