### ISSUE TITLE
Suggestion to improve the content of the final jar

### ISSUE THREAD

**Issue by nroduit** [LGoodDatePicker/LGoodDatePicker#148]
It would be nice to have a package for the demo and another for the library to reduce the size of the jar. 

Moreover, there are test classes and experimental classes that should not be in the final package.

**Comment by WiseEagleOwl** [comment]
> Moreover, there are test classes and experimental classes that should not be in the final package.

Our tests which are stored under path `Project/src/test/...` are not inclueded in the released JARs. So I'm not quite clear what you are referring to. I'm guessing things like `Project/src/main/java/com/github/lgooddatepicker/durationpicker_underconstruction/...`.
It would be very helpful if you could be more precise in what you would want *not* to be included.

Regarding the demo application as a seperate package. I concur that it would be nice but the current setup enables us to have a very simple automated CI publish release pipeline. Having multiple package which depend on one another would complicate our CI and I don't have the time required to implement this.

**Comment by BlakeTNC** [comment]
@nroduit 
> It would be nice to have a package for the demo and another for the library to reduce the size of the jar.

The demo classes are pretty small compared to both the total size of the library, and compared to other existing packages that could potentially be removed. The primary example of "extra code" that could be removed is referenced in the enhancement issue #168. If that enhancement is implemented, the jar size would go down more. I do agree with @WiseEagleOwl that moving the demo classes to an external project would be a relatively low priority, and that the work involved would be nontrivial due to our current build process. 

It may also not actually be desirable to separate the demo from the library. Right now, someone can run the demo just by double clicking the self contained main library jar (or the demo jar, which is a copy of the same file), without needing a batch file or other method to specify dependencies for the demo. There is an advantage to keeping such exploratory steps very simple for new users of the library. 

> Moreover, there are test classes <snip> that should not be in the final package.

The test classes and the JUnit dependency do not exist in the final release package. I updated the POM file documentation to emphasize this. 8f93620ea7ba55df16dca8fd750be1cddcc1208d

> and experimental classes

I agree that the library would be "cleaner" without any experimental classes. However there would be some problems with removing them.
- This library has existed for years, we don't know which specific experimental classes might actually be in use by anybody.
- Due to the above, we would not know what is safe to remove.

I also agree that this suggestion would be more useful if the exact suggested classes to remove were specified. The duration picker is my guess, but we can't know for sure what you had in mind. As far as the duration picker is concerned, I think it would probably be better to leave it in, for possible future use or development. That component definitely "fits in with the theme" of this library, it is not a misfit. Somebody might already be using it in its current form, or somebody might want to enhance it and make that particular component more mature in the future.

**Comment by BlakeTNC** [comment]
I'm closing this issue for now based on our answers to the raised items. Please comment on the issue if you have any other thoughts or suggestions. (You can still comment on a closed issue.) We could always reopen the issue if needed. Thank you for the suggestions. 

Note that the library is open to pull requests, if a developer ever wants to improve the library. For example, someone may want to further develop or test the duration picker.
