### ISSUE TITLE
About week of the year

### ISSUE THREAD

**Issue by willsuh** [LGoodDatePicker/LGoodDatePicker#20]
Hello,
Following recent update including the addition of week of the year feature, it seems that there is incompatibility within DatePickerSettings, between `setWeekNumberRules `and `setFirstDayOfWeek`.
For the below code, week starts on Sunday (`WeekFields.SUNDAY_START`), but takes no consideration of (`DayOfWeek.MONDAY`). The `WeekField ` (either `ISO `or `SUNDAY_START`) seems to have priority over `DayOfWeek `definition, setFirstDayOfWeek being useless.
```
settings.setWeekNumberRules(WeekFields.SUNDAY_START);
settings.setWeekNumbersDisplayed(true, true);
settings.setFirstDayOfWeek(DayOfWeek.MONDAY);
```
Thank you to confirm.

Regards,
Guillaume

**Comment by BlakeTNC** [comment]
Hello,
This override is on purpose to prevent the programmer from accidentally creating an ambiguous situation. Week numbers have the most clear meaning if the calendar rows display the same first day of the week that is specified in the WeekNumberRules. If you wish for the "setFirstDayOfWeek()" function to have priority, then you need to set DatePickerSettings.setWeekNumbersForceFirstDayOfWeekToMatch(false);

If you turn off forced matching of the week number rules, then you can still display week numbers and have the week start on any day of the week that you wish. However, realize that this means that some of the days in each row can, (for example), fall on "week number 1" according to the ruleset, and some of the days in the -same- row might fall on "week number 2". (When you turn off forced matching, one calendar row can span more than one week number.)

When you turn off forced matching, the calendar can (and will) still display week numbers, but it will use a "majority rules" system to decide which week number to display, instead of requiring an exact match of for all the dates that are shown in a single calendar row. For more information on the majority rule system, see the javadocs for "setWeekNumbersForceFirstDayOfWeekToMatch()".

Warm regards,
Blake

**Comment by BlakeTNC** [comment]
Just now, I edited the Javadocs a little bit, to try and make the behavior of this function a little more clear. The updated function documentation is pasted below. Thank you. -Blake

-----------------

/**
     * setWeekNumbersForceFirstDayOfWeekToMatch, This setting determines how to resolve any conflict
     * between the weekNumberRules setting and the firstDayOfWeek setting. This setting only has an
     * effect whenever weekNumbersDisplayed is true. The default value for this setting is true.
     *
     * If weekNumbersDisplayed is false, then the week numbers will not be displayed, and this
     * setting will not have any effect.
     *
     * If this setting is true and weekNumbersDisplayed is true, then the first day of the week that
     * is shown on the calendar will always match the weekNumberRules definition for "first day of
     * the week". (And all the dates in each row will always belong to the displayed week number.)
     *
     * If this setting is false and weekNumbersDisplayed is true, then the first day of the week
     * that is shown on the calendar will always match the "firstDayOfWeek" setting (instead of
     * matching the weekNumberRules). In this case, it is possible for a single calendar row to
     * contain days that fall on on more than one week number. (According to the currently set
     * weekNumberRules.) In this situation, the displayed week numbers will be determined by a
     * "majority rules" system, which is described below.
     *
     * Description of the "majority rules" system: Under the majority rule system, the calendar will
     * count the number of days in each row that belong to each week number. Four (or more) days in
     * a particular row will always match a particular week number, and that "majority week number"
     * is the week number that will be displayed next to the row.
     *
     * To prevent ambiguity, it is recommended to leave this function set to its default setting (of
     * true). If you set this setting false, then the displayed "week numbers" will be more
     * ambiguous. When this setting is false, the calendar display may not exactly match the
     * currently set weekNumberRules.
     */

**Comment by BlakeTNC** [comment]
The new Javadocs and the renamed function are included in the latest release: [LGoodDatePicker 7.2.4](https://github.com/LGoodDatePicker/LGoodDatePicker/releases). 
warm regards,
Blake
