### ISSUE TITLE
TimePicker time adjustment related issues, and more

### ISSUE THREAD

**Issue by willsuh** [LGoodDatePicker/LGoodDatePicker#31]
Hello,

TimePicker component time value can be adjusted through 3 ways: manual edit, TimeMenuButton (similar to combobox behavior), spinner.
I am encountering the following issue:
Supposing I have a TimePicker whose settings are modified as follows:
```
timeSettings.generatePotentialMenuTimes(TimeIncrement.FifteenMinutes, LocalTime.of(1, 00), LocalTime.of(12, 00));
timeSettings.setDisplayToggleTimeMenuButton(false);
timeSettings.setDisplaySpinnerButtons(true);
```
Issue 1: The spinnerbutton still allows the user to adjust time by minute increment, instead of 15-minutes increment. When using TimeMenuButton (combobox), the behavior acts as expected. I was thinking of a way to tackle this issue by setting a condition (i.e.: `time.getMinute() % 15 == 0`) in the TimeVetoPolicy, but not good since the condition is hit at every + or - adjustment. I guess TimeVetoPolicy should only receive interval condition (PickerUtilities.isLocalTimeInRange....).

Issue 2: spinnerbutton still allows the user to select time beyond the defined range (1:00-12:00). TimeVetoPolicy lets the behavior acts as expected (not necessary with TimeMenuButton adjusting method). Is it an issue?

Same above issues for manual editing.

Issue 3: spinner button adjustment reacts slowly when adjusting +/-. Any way to modify this?

Issue 4: TimePicker as editor and renderer in JTable, the corresponding table rowHeight is adjusted according to adjustment JButton. Any way to narrow the height?

Issue 5: TimePicker as editor and renderer in JTable, how to define Font color when row is selected?

Issue 6: When setting visibility of adjustment button to false (when TimePicker is used as renderer in JTable), there is still an empty space (having the width of the JButton) right after the text. Any way to avoid this? Same issue for DatePicker in JTable.

Thank you for your feedback.
Regards,
Guillaume

**Comment by willsuh** [comment]
ERRATUM: for issue 6, OK for TimePicker, NOK for DatePicker.

**Comment by BlakeTNC** [comment]
These issues should probably be entered individually. I intend to break this up into its individual issues and enter each one into the issue tracker. 
I'm starting the writing of the individual issues below.


# Feature request: Set time spinner increment values.

It would be useful to allow the "spinner style" buttons on the time spinner to increment the time value by custom values (greater than one minute).

For example:  If you set the increment to 15, then the time spinner will only increment the time values to multiples of 15 minutes. 

Technical notes:
The spinner should always increment to a time value that is an even multiple of the increment. 
Example: if the user manually sets the time to 7:03 am, and the increment is set to 15 minutes, the spinner up arrow should change the time to equal "7:15 am", not "7:18 am".

Increments must be values that divide evenly into 60 minutes or 24 hours. The possible increment values are:
1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60, 120, 180, 240, 360, 480, 720.


# Idea: Ability to set spinner button wrap times in time picker.

The default "wrapping times" for the times spinner buttons are 11:59p for the up button, and 12:00a for the down button. The idea is that the programmer can set other wrapping times for the spinner buttons so that they automatically stay within a defined time range. 

# Feature request: Increase the acceleration speed for the time picker spinner buttons.

spinner button adjustment reacts slowly when adjusting +/-. Can we increase the acceleration speed?


# Issue 4: TimePicker as editor and renderer in JTable, the corresponding table rowHeight is adjusted according to adjustment JButton. Any way to narrow the height?
Response: No, the minimum row height is automatically set as required by the time picker. If the height was that any narrower, then the component parts would not be completely visible.

# Issue 5: TimePicker as editor and renderer in JTable, how to define Font color when row is selected?
Response: The foreground and background color for selected rows is taken from the table settings. Modifying the table settings will modify these colors.

# Issue 6: When setting visibility of adjustment button to false (when TimePicker is used as renderer in JTable), there is still an empty space (having the width of the JButton) right after the text. Any way to avoid this? Same issue for DatePicker in JTable. ERRATUM: for issue 6, OK for TimePicker, NOK for DatePicker.
Response: The date picker button cannot be set to invisible, so I'm not sure what this issue is describing.
