### ISSUE TITLE
Feature Request: Set a default YearMonth to open in calendar.

### ISSUE THREAD

**Issue by bilalzafar256** [LGoodDatePicker/LGoodDatePicker#57]
Hello, 
I am very new to java, And I found this library very useful. I am using this library in my application BUT I am facing an issue.
I have set `minDate `and `maxDate ` in the calendar, before and after these dates, dates will be un-select able.
Lets say, `minDate = 01-01-2017` and `maxDate = 30-06-2017` then user will only be able to select date between these two dates.
Now, my maxDate is 30-06-2017 but today's date is 19-07-2017 and when I open the calendar popup it shows me the current month on which obviously I am unable to select any date because maxDate sets to previous month. What I want here is that when user opens the calendar popup, it should open the month of maxDate.

I have seen the documentation BUT couldn't find any help regarding this. Any reference to my solution ?

**Comment by BlakeTNC** [comment]
Hello,
  This is a valid issue. I've implemented the ability to set the default YearMonth in DatePickerSettings. I also added a usage example for the new feature to the full demo. (See date picker number 19 in FullDemo.java)

I've tested the feature and committed it to the repository, but the code will need to be tested out a little bit by others developers before being declared stable. It turns out that the required changes were unusually complex in their implications, so I hope that both the new feature works as desired, and that the new feature does not modify anyone's old functionality. Please let me know if everything seems to work as expected for you.

Since  a new official release that includes the new feature could be a few weeks or months into the future, I attached a compiled copy of the repository to this message for your convenience. (With the new set default month feature). 

Warm regards,
Blake

[LGoodDatePicker-10.3.2-BETA.zip](https://github.com/LGoodDatePicker/LGoodDatePicker/files/1159970/LGoodDatePicker-10.3.2-BETA.zip)

**Comment by BlakeTNC** [comment]
PS, Our "star" ratings help other developers find this project. Only if you like, please add a star to the project at the upper right corner of the [LGoodDatePicker main project page](https://github.com/LGoodDatePicker/LGoodDatePicker).
