### ISSUE TITLE
How to implement

### ISSUE THREAD

**Issue by chrisrudd812** [LGoodDatePicker/LGoodDatePicker#64]
I am new to Java and programming in general. Have never used GitHub. 
I need to implement a time picker in my project and this seems like a great solution. With jDatepicker, i just dragged a Swing container into my project. How do I go about downloading/installing/implementing this into my project using Netbeans 8.2?
Thanks

**Comment by BlakeTNC** [comment]
Hello,
 For typical usage, take a look at the "BasicDemo" file [here](https://github.com/LGoodDatePicker/LGoodDatePicker/blob/master/Project/src/main/java/com/github/lgooddatepicker/demo/BasicDemo.java).  

To manually add the component library to your project, you will need to download a copy of the jar file from the release page. Once you have the jar file, including the jar into your existing project is done in the same way as other library. Alternatively, you could automatically add the jar using Maven. (This project is included at maven central.)

The process for adding external Swing components to a visual designer pallet (so that you can drag and drop components) is specific to each IDE or designer program. To add the date picker Swing components to the NetBeans visual designer, you would need to see the NetBeans visual designer documentation, you would specifically look for how to add external components to the design palette.

May I suggest searching for the following types of instructions using Google:
"How to add a library jar to a NetBeans project"

For slightly more advanced learning, you could also search for instructions of how to create a maven project in NetBeans, or how to added new library from maven central to your POM file. After a bit of a learning curve, using maven can make it easier to manage multiple project dependencies. For a project with only one or two dependencies, adding a jar file directly might be a simpler way to start.

Warm wishes.
BlakeTNC

**Comment by chrisrudd812** [comment]
Thanks Blake. I got it installed into Netbeans palette and am looking forward to using it.

**Comment by chrisrudd812** [comment]
Thanks Blake. I have the pickers implemented but was wondering if there is a way to change the increments, for example something like: myTimePicker.setIncrement(minutes)?
