### ISSUE TITLE
False invalid Date

### ISSUE THREAD

**Issue by bojorquezja** [LGoodDatePicker/LGoodDatePicker#74]
Hi,

Great job!. 

I want to report thar when i create a DatePicker with DatePickerSettimg like .getSettings().setFormatForDatesCommonEra("dd/MM/yyyy");

When i execute the aplication, every date i select shows in red, so is invalid. Y downgrade to version 10.3.1 and it doesn't have this issue.

**Comment by WiseEagleOwl** [comment]
@bojorquezja 
The problem you are describing was a regression in 10.4.1 where formatter strings with `YearOfEra` (`yyyy` pattern) instead of Year (`uuuu` pattern) were not accepted.
This regression has been fixed with the PRs #80 and #81.
Your code `.getSettings().setFormatForDatesCommonEra("dd/MM/yyyy");` should be working with the current *master* version.
Feel free to leave a comment if this hasn't solved the issue for you.
