### ISSUE TITLE
When changing the Formatpattern, the Border around selected date disappears.

### ISSUE THREAD

**Issue by Toni-STF** [LGoodDatePicker/LGoodDatePicker#86]
By default the selected date is surrounded by a border. After doing `dateSettings.setFormatForDatesCommonEra("dd.MM.yyyy");` the border doesn't appear anymore and the textfield will be cleared everytime you press the calenderbutton.

**Comment by WiseEagleOwl** [comment]
Hello @Toni-STF 
It's not yet clear to me what causes your issue. From your description it seems to me that the *DatePicker* keeps clearing the text content of the date text field. This can occur if the selected date string cannot be re-parsed successfully. Can you please check if `yourDatPicker.isTextFieldValid()` returns `true` or `false`?
If it continously reports `false` there is an issue with your selected *DateFormat*. There were various different issues regarding the date parsing (#76, #74) that are fixed in the current *master*.
If you are using version 10.4.1 there is a specific bug that does not allow formatter strings containing `YearOfEra` (`yyyy` pattern). To work around this you can use `Year` instead (`uuuu` pattern) which should be accepted even in version 10.4.1.

**Comment by WiseEagleOwl** [comment]
*LGoodDatePicker* release `v11.0.0` conatins fixes for the issues #76 and #74 mentiond in my previous comment. If you are still having problems with this new release feel free to reopen this issue or creating a new one.
