### ISSUE TITLE
Can't remove JTextField border

### ISSUE THREAD

**Issue by PabloPadilla5** [LGoodDatePicker/LGoodDatePicker#89]
![issue](https://user-images.githubusercontent.com/42223362/87976132-34514a00-ca92-11ea-90ba-f74063e02a7a.png)

i tried this code: 
```
JTextField datePickerField = datePicker.getComponentDateTextField();
datePickerField.setBorder(BorderFactory.createEmptyBorder());
```
but it doesn't work, is there any way to remove that border?

**Comment by WiseEagleOwl** [comment]
Hello @PabloPadilla5. Your code works fine on Windows. 
I tested these two variations, both successfully remove the text field border:
```Java
// replace border with emtpy one
datePicker.getComponentDateTextField().setBorder(BorderFactory.createEmptyBorder());
// set null as border object
datePicker.getComponentDateTextField().setBorder(null);
```
The problem is that the display of Java ui components is heavily dependent on the used platform look & feel. From your screenshot I'm guessing you are not using Windows. You will have to investigate how your platform specific look & feel handles text field borders. A good starting point could be [this stackoverflow thread](https://stackoverflow.com/questions/2281937/swing-jtextfield-how-to-remove-the-border).
